server 
{
    listen 127.0.0.1:4243;
    error_page ./tmp/www/error.html;
    max_body_size 2097152; # 2 mb => bytes ? -> 1024kb * 1024byte * 2==  

    # Define a root for the static website
    location /
	{
        allow_methods GET;
        root ./tmp/www;
        index index.html;
<<<<<<< HEAD
		autoindex on;
=======
>>>>>>> 43a25c45afca9c9962f9fd388bbdbc5365af5109
    }

    # Define a route for the Doxygen documentation
    location /doc
    {
        allow_methods GET;
<<<<<<< HEAD
        root ./tmp/www;
=======
        root ./doc/html;
>>>>>>> 43a25c45afca9c9962f9fd388bbdbc5365af5109
        index index.html;
    }
}

server
{
    listen 127.0.0.1:4244;
    max_body_size 2097152; # 2 mb
    error_page ./tmp/www/error.html;

    # Define a route for CGI testing
    location /
    {
        allow_methods GET POST;
        root ./tmp/www;
        autoindex on;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
        cgi .sh /bin/bash;
<<<<<<< HEAD
		
    }
	location /upload
	{
		methods GET POST;
		root ./tmp/www;
		allow_upload on;
	}
=======
    }
>>>>>>> 43a25c45afca9c9962f9fd388bbdbc5365af5109
}

server
{
    listen 127.0.0.1:4245;
    max_body_size 536870912; # 512 MiB
	error_page ./tmp/www/error.html;
	
    # Define a route for upload and DELETE request testing
    location /
    {
        allow_methods GET POST DELETE;
        root ./tmp/www;
        autoindex on;
        allow_upload on;
    }
<<<<<<< HEAD

	location /upload
	{
		methods GET POST;
		root ./tmp/www;
		allow_upload on;
	}
=======
>>>>>>> 43a25c45afca9c9962f9fd388bbdbc5365af5109
}